version: '3.9'

services:
  redis:
    image: redis:3.2.6-alpine

  app:
    build: .
    environment:
      - SQSHOST=http://localstack
      - SQSPORT=4566
      - SNSHOST=http://localstack
      - SNSPORT=4566
      - PYTHONPATH=/app
    volumes:
      - .:/app
    links:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    expose:
      - "4510-4530"
      - "4566"
      - "4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - SQS_PROVIDER=elasticmq
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
