site_name: Melange
repo_name: Rydra/melange
repo_url: https://github.com/Rydra/melange

# Config file inspired by:
# - https://github.com/mkdocstrings/mkdocstrings/blob/master/mkdocs.yml
# - https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# - https://github.com/tiangolo/fastapi/blob/master/docs/en/mkdocs.yml

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true

extra_css:
- css/mkdocstrings.css

nav:
    - Home:
      - Overview: index.md
    - Getting started:
      - Tutorial: tutorial/getting-started.md
    - Building blocks:
        - Messaging Backends: components/messaging-backends.md
        - Serializers: components/serialization.md
        - Message Dispatcher and Consumers: components/consumers.md
        - Publishers: components/publishers.md
        - Factory: factory.md
        - Advanced topics:
            - Default messaging backend: components/advanced-topics/default-mb.md
            - Message Deduplication: components/advanced-topics/message-dedup.md
            - Behind the scenes: components/advanced-topics/behind-scenes.md
    - Testing:
      - Testing with Melange: testing.md
    - Examples:
      - Overview: examples/index.md
      - Payment Service: examples/payment-service.md
      - SAGA choreography: examples/saga-choreography.md
    - Roadmap:
      - Roadmap: roadmap.md
      - External links: mixed-bag.md
    - Code Reference:
        - Publishers: api-reference/publishers.md
        - Consumers: api-reference/consumers.md
        - Serializers: api-reference/serializers.md
        - Messaging Backends: api-reference/messaging-backends.md
        - Factory: api-reference/factory.md
