site_name: Melange
repo_name: Rydra/melange
repo_url: https://github.com/Rydra/melange

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true


nav:
    - Melange: index.md
    - Tutorial - Getting started: tutorial/getting-started.md
    - Building blocks:
        - Messaging Backends: components/messaging-backends.md
        - Serializers: components/serializers.md
        - Message Dispatcher and Consumers: components/consumers.md
        - Publishers: components/publishers.md
        - Factory: factory.md
    - Advanced topics:
        - Advanced topics: advanced-topics.md
        - Behind the scenes: behind-scenes.md
    - Examples: examples.md
    - Testing: testing.md
    - Roadmap: roadmap.md
    - Mixed bag of ideas: mixed-bag.md
    - Code Reference:
        - API reference: api-reference.md
