site_name: Melange

theme:
  name: material
  features:
    - content.code.annotate


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true


nav:
    - Melange: index.md
    - Tutorial - Getting started: tutorial/getting-started.md
    - Building blocks:
        - Messaging Backends: components/messaging-backends.md
        - Serializers: components/serializers.md
        - Consumers: components/consumers.md
        - Publishers: components/publishers.md
        - Factory: factory.md
    - Examples:
        - Payment service: examples/payment-service.md
        - Saga choreography: examples/saga.md
    - Code Reference:
        - API reference: api-reference.md
