site_name: Melange

theme:
  name: material
  features:
    - content.code.annotate


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings


nav:
    - Home: index.md
    - Examples: examples.md
    - Code Reference:
        - API reference: api-reference.md
